### ISSUE TITLE
Unclear how to update the db

### ISSUE THREAD

**Issue by damonlynch** [fedora-python/portingdb#12]
I'm the developer of one of the packages listed in the database, rapid-photo-downloader. I'm porting it to Python 3 (and Qt 5 and a bunch of other packages). From either the main page or the page dedicated to the application, I can't figure out the best way to let whoever is responsible know for the database that the application is in fact being currently ported. 

There is the statement "(Note that there might be false positives; if you spot one, please file a bug)". Is that meant to apply to cases like this?

**Comment by sYnfo** [comment]
I'd say this is among the best ways of contacting us. :)

@encukou is working on addressing this issue, I believe. I've started writing a blog post on how to contribute to portingdb [0] that should help people with issues like this -- it's still a draft, but would it be helpful to you? Is there maybe something you would improve?

[0] http://synfo.github.io/2015/10/14/Porting-Database/

**Comment by encukou** [comment]
Hi,
This is indeed the best way to start a conversation.
Your project is now marked as `in-progress`. You can look at 1abd2265d1 to see how the update looks.

Thanks for letting us know!
