### ISSUE TITLE
False positive with dateutils15: upstream dateutils 2.x is py3

### ISSUE THREAD

**Issue by Arthur2e5** [fedora-python/portingdb#120]
It seems that https://portingdb-encukou.rhcloud.com/pkg/python-dateutil15/ causes maintainers to mark both of the python packages that depends on it as *dependencies unmet*. However, dateutils15 is intended to be py2 only, and its Python3 port is maintain upstream as dateutils 2.x.

PS. Both packages that depends on dateutils have Python 3 support upstream:

* python-tgscheduler: Since https://pypi.python.org/pypi/TGScheduler/1.7.0.
* python-vobject: Since https://pypi.python.org/pypi/vobject/0.9.0.

**Comment by encukou** [comment]
Thanks for the report! I've marked python-dateutil15 as dropped.

I added the [Bugzilla bug for vobject](https://bugzilla.redhat.com/show_bug.cgi?id=1304750) to the [Python3 tracking bug](https://bugzilla.redhat.com/show_bug.cgi?id=PYTHON3).
