### ISSUE TITLE
Track packages with py2 only binaries

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingdb#132]
We could automatically find packages that provide 2 subpackages (for 2 and 3) but only the python2 subpackage has something in /usr/bin.

Than we could mark them as mispackaged.

I think we have plenty of those packages in Fedora. See for example https://bugzilla.redhat.com/show_bug.cgi?id=1323256

**Comment by encukou** [comment]
The DNF plugin is currently pretty naïve when it comes to finding corresponding py2/py3 packages: basically, it just compares the number of subpackages with py2 dependencies to the number of subpackages with py3 dependencies. (This gives false positives, e.g. [authconfig](http://fedora.portingdb.xyz/pkg/authconfig/) is now categorized manually.)
This would need some more detailed analysis. But getting the info about file provides shouldn't be hard.

**Comment by hroncok** [comment]
I'm not very familiar with portingdb internals, but the idea with repoquery is:

    repoquery -l python-pygments --releasever rawhide | grep ^/usr/bin
    repoquery -l python3-pygments --releasever rawhide | grep ^/usr/bin

Where the first provides results and the second one does not. And we already know what py2 and py3 subpackages are generated form the SRPM.

**Comment by hroncok** [comment]
We can be naive as well and countfiles in /usr/bin for both py2 and py3 packages and compare that somehow. We can raise the flag when py3 packages have none of such files, but py2 packages do.

**Comment by irushchyshyn** [comment]
Created a PR #249 with the implementation for this.

As a result, there are around 30 packages affected. The list of packages:

- PyXB
- ahkab
- gdal
- lcgdm
- netcdf4-python
- pystache
- python-acme
- python-aexpect
- python-bugzilla
- python-docutils
- python-doit
- python-fiat
- python-gearbox
- python-igor
- python-igraph
- python-jsonschema
- python-ly
- python-ndg_httpsclient
- python-ngram
- python-oslo-policy
- python-oslo-privsep
- python-oslo-rootwrap
- python-pbr
- python-py2neo
- python-pygments
- python-rosdep
- python-rosinstall
- python-whisper

**Comment by hroncok** [comment]
I've recently came across `python-docutils` (`rst2html`) and wanted to report. Will you do some mass bug filling?

**Comment by irushchyshyn** [comment]
I was thinking, if we want to do mass bug filling if this gets merged, or if we should first send some warning to the mailing list?

**Comment by hroncok** [comment]
Every mass filling requires an e-mail first https://fedoraproject.org/wiki/Mass_bug_filing

**Comment by irushchyshyn** [comment]
Thanks for the link Miro, did not know that.

**Comment by hroncok** [comment]
Also, from the guidelines:

> If the executables provide the same functionality independent of whether they are run on top of Python 2 or Python 3, then only the Python 3 version of the executable should be packaged. **Transitioning from python2 to python3 is left to individual package maintainers except for packages in Fedora's critical path. For these, we want to port to python3 versions in the same Fedora release if possible.**

I'd suggest we try to change the highlighted part to:

> Transitioning from python2 to python3 is left to individual package maintainers, but strongly encouraged. (Except for packages in Fedora's critical path. These shall be changed to python3 as soon as technically possible.)

I will open a FPC ticket unless there are other suggestions.

**Comment by irushchyshyn** [comment]
If transitioning is currently only encouraged but is up to maintainers, then should it be enforced with mass bug filing? On the mailing list I have received a couple of responses that Py2 binaries are intended for some packages on the list.

**Comment by encukou** [comment]
I don't think mass bug filing counts as enforcement. For most packages it would be a reminder – in most of these it's oversight on the maintainer's part, rather than intention. You can word the bugs as questions – did you really want to do that?
Of course, for packages where we know this is intentional, the bug shouldn't be filed. Could you add notes to portingdb for these packages?

**Comment by irushchyshyn** [comment]
Of course, I can add notes for those packages. Thanks for clarifying this for me.

**Comment by irushchyshyn** [comment]
@hroncok can we close this issue?
Packages with py2 only binaries are already marked as *mispackaged* and we have a tracking bug for those: https://bugzilla.redhat.com/show_bug.cgi?id=1432186

**Comment by encukou** [comment]
Closing, feel free to reopen if needed.
