### ISSUE TITLE
Subpackages not taken into account when determining python3 status

### ISSUE THREAD

**Issue by puiterwijk** [fedora-python/portingdb#143]
python-fedora has a subpackage set python3-fedora* where the bits that are useful for python3 are available for python3, but it is marked as not available for python3.

**Comment by encukou** [comment]
Indeed, subpackages aren't taken into account; portingdb works at the level of the whole SRPM. I can't automate getting status information for individual subpackages – at least not as easily as for whole packages.

That leaves tracking the information manually. For `python-fedora` I did it in https://github.com/fedora-python/portingdb/commit/4c2397d3649d26698fb6d534cdbbe27f08fa58ab; if you have anything to add please let me know.
