### ISSUE TITLE
Repo & Deployment access

### ISSUE THREAD

**Issue by ralphbean** [fedora-python/portingdb#15]
In preparation for the porting fad this weekend, can we open up the group of people who can update the app some?  This way, everyone can be a little more coordinated in their tasks and they can show off the fruits of their labor more quickly.. with less friction.  We'll need people who can:

- push to github
- push to openshift

Can I request that myself and @abadger be added to the github group?  For openshift, my openshift account is associated with ralph.bean@gmail.com and @abadger is associated with a.badger@gmail.com.

**Comment by sYnfo** [comment]
@ralphbean I believe the app is set to automatically redeploy on new commits (though @encukou will know for sure).

I've sent you and @abadger an invite to the fedora-python group

**Comment by encukou** [comment]
A push to Openshift will trigger a redeploy, but it does take a minute to update the DB, so I worry that simultaneous pushes might not be good for the system. (worry == I don't want to start trying it at the FAD)
I'm happy to hand out access if you send me your SSH keys, but we should coordinate so that there's only one person pushing at a time. How do hand-overs either here or on IRC sound?

**Comment by ralphbean** [comment]
Yeah, let's just rely on the auto re-deploy behavior.  That seems easiest.  Will see you in IRC tomorrow.  Thanks!

**Comment by ralphbean** [comment]
Odd, I pushed cce047bbdc19f7ec1def5b5a34088d3b3371ffc4 but [the app](http://portingdb-encukou.rhcloud.com/pkg/python-shove/) didn't seem to update.  (It worked locally when I tried serving the app).

**Comment by encukou** [comment]
I see I could have worded that better, sorry.
A {*push to OpenShift*} will trigger a redeploy. Not a push to GitHub.

**Comment by ralphbean** [comment]
Ah, I see.  Could you add ssh keys for myself and @abadger?

- @ralphbean is [here](https://github.com/ralphbean.keys)
- @abadger is [here](https://github.com/abadger.keys)

**Comment by encukou** [comment]
Added.
Sorry for not responding earlier, I was at PyCon and lost this comment in the storm of pull requests e-mails :(

**Comment by encukou** [comment]
Aaaand the remote is ssh://560d3fd12d5271847c000146@portingdb-encukou.rhcloud.com/~/git/portingdb.git/

**Comment by ralphbean** [comment]
Thanks @encukou!
