### ISSUE TITLE
Need a way to mark that upstream prefers not to have Python 3 support

### ISSUE THREAD

**Issue by michel-slm** [fedora-python/portingdb#16]
The upstream for the entire stack of Obnam and its dependencies has indicated that currently he prefers not supporting Python 3 -- is there a way to mark this so that for the Python 3 porting page people do not waste their time either contacting upstream or working on the port?

   http://listmaster.pepperfish.net/pipermail/obnam-dev-obnam.org/2015-October/000238.html

**Comment by sYnfo** [comment]
I'd say marking the packaged as dropped and adding a note saying upstream is not interested and what the alternative is, if any, should be enough for now. :)

**Comment by encukou** [comment]
A hacky workaround, but I won't have time to implement a better solution before the FAD this weekend, so let's use it. I'll leave the issue open.

YAML allows marking multiple packages with the same status & note; see the commit.

**Comment by michel-slm** [comment]
@encukou nice, thanks! Agreed, will leave this open for now

**Comment by rapgro** [comment]
Well, when upstream refuses to Python3, we can remove the package in the long run as upstream prefers to die. How long can Fedora still support Python2, optionally?
Elsewise :+1: here.

**Comment by encukou** [comment]
Wow, this issue is old :)

The `dropped` status for obnam was reverted in cd9d9e37a362a4b7a688c8eefe5153e3bee9fb93.

Nowadays, the `dropped` status means that an alternative is available. If there's no alternative yet, anyone can pick up the work. If upstream doesn't want to accept patches, forking is always available.
