### ISSUE TITLE
Add minimum width requirement for bar items

### ISSUE THREAD

**Issue by tradej** [fedora-python/portingdb#2]
Currently, the bars are proportionate in any case, which leads to small-number items being invisible (highlighted in the picture). Please add minimal width.

![portingdb](https://cloud.githubusercontent.com/assets/1138123/10511284/6e8060be-7338-11e5-9d0c-4b7a29a46751.jpg)

**Comment by encukou** [comment]
The whole point of the progress bar segments is to be proportionate; the label is just secondary.
I've moved the counts and labels below the bars to make them readable. I hope it's an acceptable solution.

**Comment by tradej** [comment]
Thank you, the current solution certainly helps legibility as requested, albeit I still don't find it particularly pretty. Since I filed this bug on behalf of Jan Beran, I will ask him if the solution is satisfactory for him.

**Comment by encukou** [comment]
I've removed labels from the bars altogether, which should make them prettier.

**Comment by tradej** [comment]
Yes, it looks nice and comprehensible, thank you.
