### ISSUE TITLE
Need to report if Python package has Python3 version available in PyPI

### ISSUE THREAD

**Issue by rodrigc** [fedora-python/portingdb#23]
These two applications:

http://caniusepython3.com/
https://python3wos.appspot.com/

poll PyPI directly to report if a Python3 version of a package is available.

The portingdb should report info from PyPI.  This will allow people to see
if the Python3 package is available upstream, but the newer version is not in Fedora.
This will give people the idea that the focus should be on the Fedora packaging,
and not the Python3 code of the package itself.

**Comment by encukou** [comment]
Well, portingdb is most effective for packages that are not on PyPI (OpenStack, yum/dnf, pitivi, ...)

But automatically mapping between RPMs and PiPI would be useful, yes.

**Comment by rodrigc** [comment]
Agreed, not every Python software is on PyPI.  However, for the ones that are,
reporting the PyPI information about Python3 would be helpful.

**Comment by rapgro** [comment]
:+1:

**Comment by hroncok** [comment]
I think it is now obvious that we won't do this. Automatic mapping between RPMs and PyPI would be useful, but is doesn't help with our goal: track what packages in Fedora depend on Python 2.
