### ISSUE TITLE
Need to put comments at the top of each yaml file

### ISSUE THREAD

**Issue by rodrigc** [fedora-python/portingdb#25]
It is hard to figure out which yaml file I need to modify to indicate
that I am working on a package.
If each yaml file had comments at the top, that would make things a lot easier to figure out.

**Comment by encukou** [comment]
Sorry it's confusing!
These are explained in detail in "Where Porting Happens" in the right column on [the page](http://portingdb-encukou.rhcloud.com/). But if more people are confused by this, it would indeed be helpful to put the comments in the source files themselves.

**Comment by encukou** [comment]
Please re-open the bug if you find more people hitting this issue.
