### ISSUE TITLE
python-cli package is "discontinued"

### ISSUE THREAD

**Issue by gtema** [fedora-python/portingdb#251]
as I've mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1311516#c5 the python-cli package is not supported anymore. So might be make sense to mark it as deprecated (I don't think it worth overtaking the project as it does not look very popular).
On the other hand it is marked as a dependency of openerp7, which, as stated in portingdb (http://fedora.portingdb.xyz/pkg/openerp7/), is also not interested in port to python3. But even here there is probably an issue with packaging, since requirements.txt of https://github.com/odoo/odoo/blob/10.0/requirements.txt do not contain python-cli package, was never in commit history, is not listed in the provided rpms (http://nightly.odoo.com/7.0/nightly/rpm/)

**Comment by encukou** [comment]
I've added a note that it's unmaintained.

If you want to get it dropped from Fedora, please work with its current maintainer. Portingdb is just a dashboard. (The “dropped” status in portingdb is only for packages that have a viable replacement in Fedora. This is a service to maintainers of dependent packages, who might want to start porting. Without a replacement, marking something as dropped isn't very useful.)

I don't think solving the packaging problems of openerp7 is very important, but feel free to open a bugzilla for it.

**Comment by gtema** [comment]
Thanks Peter,

python-cli drop bug is raised - https://bugzilla.redhat.com/show_bug.cgi?id=1428738
