### ISSUE TITLE
Track Python 2 mispackaged packages

### ISSUE THREAD

**Issue by irushchyshyn** [fedora-python/portingdb#268]
Create a separate status for Python 2 (sub)packages which are named `python-foo` instead of `python2-foo` (with provides) and should be renamed in the nearest future.

There are packages like this across all statuses, so suggestions on displaying those in portingdb can be added to comments. 

Update:

* Name status should be a boolean field
* There should be 2 statuses: Correctly named and Incorrectly named
* Collect also information on cases like `sympy` (`foo`, `python3-foo`), which should also go into incorrectly named group

**Comment by encukou** [comment]
Let's have the data before thinking about how to display it. Visualizations always depend on the data.

**Comment by irushchyshyn** [comment]
TODO:
Prioritize misnamed packages, depending on how many other packages list them in `Requires`.

**Comment by irushchyshyn** [comment]
Closing the ticket, all implemented in the linked Pull Requests.
Prioritization is no longer needed, as most misnamed packages have already been renamed. Please reopen if needed.
