### ISSUE TITLE
Add explanation of statuses

### ISSUE THREAD

**Issue by tradej** [fedora-python/portingdb#3]
The statuses (**I**, **P**, ✔, **X**, **B**) are not explicitly explained. Please add an explanation to the top of the page.

**Comment by encukou** [comment]
I hope this explains them enough

**Comment by tradej** [comment]
I am afraid it does not. From the current state of things, I can't quite make out what e. g. "Blocked" means (unported dependencies upstream, in Fedora only etc. Now consider I'm a manager completely unfamiliar with the matter).

I really like the boxes with descriptions on the right side:

> **In Progress**
> *Patches for Python 3 support are being written or tested.*

However, those only cover the statuses that are currently present in the respective channels (upstream, Fedora, etc.), and having the information only there does not seem as a particularly user friendly solution to me. Could you replace the one-liner info below the horizontal bars with the same boxes, please?

Thank you.

**Comment by encukou** [comment]
Alright, the status legend is back. Is this iteration OK?

**Comment by encukou** [comment]
Looks OK
