### ISSUE TITLE
Idle packages marked as Released upstream

### ISSUE THREAD

**Issue by encukou** [fedora-python/portingdb#302]
Bugs should be filed as packages' dependencies are ported. Portingdb has a script to detect these; currently we're at three:
```
$ python3 -m portingdb -v upstream-idle 

The following packages are both 'idle' and marked as 'released' upstream:

        autokey
        mpi4py
        wxPython
```

**Comment by irushchyshyn** [comment]
> autokey

There is only a Python 3 fork available for `autokey`, so it should be packaged as a separate package.

> mpi4py

Opened [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1461023)

> wxPython

There was already a [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1322501) opened for this package. `wxPython Phoenix` should be packaged separately as per comments in the bug,  and there is a place-holder [review request ](https://bugzilla.redhat.com/show_bug.cgi?id=1310434)for it already.

**Comment by irushchyshyn** [comment]
Currently, the output of the command is:

```
$ python3 -m portingdb -v upstream-idle 

The following packages are both 'idle' and marked as 'released' upstream:

	python-ironic-inspector-client
	python-muranoclient
	python-pyudev
```
Created:
https://bugzilla.redhat.com/show_bug.cgi?id=1560487
https://bugzilla.redhat.com/show_bug.cgi?id=1560485
https://bugzilla.redhat.com/show_bug.cgi?id=1560484

Closing the issue. Please reopen if needed.
