### ISSUE TITLE
Mention Pull Requests in howto?

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingdb#333]
Currently we say attach the patch to bugzilla in http://fedora.portingdb.xyz/howto/

Maybe we want to say "open a Pagure Pull Request" instead?

**Comment by irushchyshyn** [comment]
I think it is a good idea. I am going to update it.

**Comment by irushchyshyn** [comment]
Howto page updated in #335.
Can be viewed already: http://fedora.portingdb.xyz/howto/

Closing the issue. Please reopen if needed.

**Comment by ari3s** [comment]
As am not a packager, I am not allowed to use git on Fedora Pagure even I have FAS account. I can only make Pagure PR via Web UI which is poor. You can check [Allow PRs for non-packagers](https://pagure.io/fesco/issue/1770).

**Comment by hroncok** [comment]
The how to explicitly says:

> (if you are not a Fedora packager yet, you may use remote pull requests)

What's wrong with that?

**Comment by ari3s** [comment]
O.K. So I understand now that we mean the same way, sorry for my ignorance. I would rather propose to keep the both options - Pagure PR for packagers as the preferred way, and either the remote (I would say Web UI) Pagure PR or bugzilla patch for non-packagers.

**Comment by irushchyshyn** [comment]
@ari3s , thank you for the suggestion. We have updated the How-to page, so for non-packagers it now says:
```
if you are not a Fedora packager yet, you may use remote pull requests
or attach a patch to the Bugzilla ticket
```
Feel free to let us know if you see any other issues.
