### ISSUE TITLE
Handle version-independent packages

### ISSUE THREAD

**Issue by encukou** [fedora-python/portingdb#353]
There are some python-version-independent packages, where an unversioned `python` in the name is correct. https://github.com/fedora-python/portingdb/pull/352 dealt with `*-doc`, but there are others. What to do with them? 
Worth checking are:

```
python-django-bash-completion
python-matplotlib-data
python-matplotlib-data-fonts
python-qt5-rpm-macros
python-rpm-macros
python-sphinx-locale
python-srpm-macros
python-typeshed
```

**Comment by irushchyshyn** [comment]
I believe we can create a white list for packages like that, and ignore them as well when checking misnamed requirements.

**Comment by irushchyshyn** [comment]
From the second glance, those are the packages, which are named `python-smth` but which do not in fact require Python.
So they are most probably already ignored, as we check if the requirement is both [misnamed and tracked in portingdb](https://github.com/fedora-python/portingdb/blob/master/dnf-plugins/py3query.py#L266) (`all_provides` is generated from all portingdb packages).
For example, `python3-mypy` requires `python-typeshed`, but is not classified as  `Misnamed Requires` group in portingdb.
I am going to check it closer though.

**Comment by encukou** [comment]
Yup, sometimes the answer to "we should check this" is "all is OK" :)
Thanks for checking though!

**Comment by irushchyshyn** [comment]
Right, I did check those in the list, and because they are not tracked in portingdb and do not require Python, they are not considered ambiguous requirements. So it should be fine.
