### ISSUE TITLE
Filter out modules

### ISSUE THREAD

**Issue by encukou** [fedora-python/portingdb#385]
In the last update, packages like `django` or `python-django-pipeline` gained subpackages like `python2-django-1.6.11.6-12.module_1f1233d9` and `python2-django-pipeline-1.3.27-11.module_0b083f9b`.

Let's just make portingdb ignore these. If a package needs Python 2, then I guess in the long term we actually *want* it to use python2 from a module. (And we don't want to maintain such a module.)

**Comment by irushchyshyn** [comment]
Given that in the following update (#388) all the modules got filtered out, I am tempted to think that this was some build system error which got fixed and we do not have to do anything.

But just in case it is not so and it happens again, a possible fix could be [this](https://github.com/irushchyshyn/portingdb/commit/7f358940ae727466fdc582d41419e07322050366).

**Comment by encukou** [comment]
Thanks :)
