### ISSUE TITLE
Mapping of statuses to Bugzilla unclear

### ISSUE THREAD

**Issue by tradej** [fedora-python/portingdb#4]
Currently, it is not clear how the statuses map to Bugzilla. Please add an explanation in a prominent place.

**Comment by encukou** [comment]
They don't map to Bugzilla.

I plan to add Bugzilla integration when we add Bugzilla links to more packages. Before that it's premature, IMO.

**Comment by tradej** [comment]
Understood. Please keep the bug open for when the BZ integration is added.

**Comment by encukou** [comment]
Added.
Bugs have their separate status; a non-NEW bug on an `idle` package turns it into `in-progress`.
