### ISSUE TITLE
Build time dependency graph

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingdb#402]
We seem to track build time dependencies now. See how [asciidoc](http://fedora.portingdb.xyz/pkg/asciidoc/) has plenty build time dependent packages. Yet in our [dependency graph](http://fedora.portingdb.xyz/graph/) there is no big cluster around it.

Could we please have a second, build-time dependency (possibly combined with runtime) graph?

**Comment by irushchyshyn** [comment]
I think we can add an option on the graph page to load build deps as well. I will try to prepare a PR for it today.
