### ISSUE TITLE
RFE: Summary by packager

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingdb#414]
I've juts found out that one of my packages (openscad) requires python2 by accident.

I would like to check all of my packages and having a page at portingdb with my packages would be very helpful. See https://pagure.io/fedora-misc-package-utilities/blob/master/f/find-package-maintainers for how to get the info.

**Comment by frenzymadness** [comment]
I don't know portingdb internals but IMHO this todo list might describe this RFE implementation:
- [ ] Add a new table to handle packagers' logins with foreign key to packages
- [ ] Add a way to download/update JSON file from pagure.io
- [ ] Add a new section to `load_from_directories()` which loads data from JSON file to database
- [ ] Add a new CLI command to check "my packages"
- [ ] Add a new web page with info about all packages and their maintainers with some JS search/filter

What do you think? If this is correct, I can try to implement it.

**Comment by encukou** [comment]
You can skip the database, just load a dict from JSON.
I'm trying to (slowly) get rid of the DB.
See the load_data module.

**Comment by hroncok** [comment]
https://src.fedoraproject.org/extras/pagure_owner_alias.json

**Comment by hroncok** [comment]
I'd say:

 1. Download that json when updating data, store it in the data folder
 2. Crete a page that shows a detail for one maintainer (similarly how groups do it)
 3. Create a page with a sorted list of maintainers with links to above

**Comment by encukou** [comment]
Instead of your 3., I went with:

3. Link to maintainer pages from package pages

**Comment by frenzymadness** [comment]
Thank you! Now I can drop all python2- subpackages from packages of mine.

**Comment by hroncok** [comment]
Only the ones that nothing depends on, please.
