### ISSUE TITLE
python2-networkx is not tracked

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingdb#459]
Can we somehow add python2-networkx package manually?

See https://bugzilla.redhat.com/show_bug.cgi?id=1634570#c3

**Comment by encukou** [comment]
Hmm. It's not a Python package:
```
dnf repoquery --repo=rawhide -l python2-networkx
/usr/share/doc/python2-networkx
/usr/share/doc/python2-networkx/README.rst
/usr/share/licenses/python2-networkx
/usr/share/licenses/python2-networkx/LICENSE.txt
```
Obviously the "almost-leaf" thing is not perfect. I'm not sure how to best fix this, however; I'll need to think/experiment a bit.

For a workaround, do the same thing as for python2-matplotlib – keep the subpackages manually. That's better than adding python2-networkx, IMO.

**Comment by hroncok** [comment]
It's a python2 metapackage. It exists just to bring in python2-networkx-xxx.

**Comment by encukou** [comment]
Also, python2-networkx was removed by the maintainer...
