### ISSUE TITLE
Handle cases where the maintainer chooses to ignore the Mass Python 2 Package Removal change.

### ISSUE THREAD

**Issue by encukou** [fedora-python/portingdb#490]
Currently these are marked `dropped`, but that's not the right way to handle them:
* <s>cairo-dock-plug-ins</s> (https://github.com/fedora-python/portingdb/pull/575)
* python-mecab
* skf

**Comment by encukou** [comment]
This is not a priority unless we start getting more of them.
I'm assigning myself in the sense of "talk to me if you want to do this".

**Comment by hroncok** [comment]
Both python-mecab and skf are gone. We should close this when we update the data.
