### ISSUE TITLE
Python 3 only packages with Python 2 dependencies

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingdb#492]
I'd like to see packages that are marked Python 3 only but have Python 2 dependencies.

If a separate new category is overkill, a summary page would do.

Usually this marks a big mistake in packaging. I've noticed we have a quite a few, when I've seen the graph from https://github.com/fedora-python/portingdb/pull/491

**Comment by encukou** [comment]
I suspect there's also a lot of build-time binaries that happen to run on Python 2.

I won't have time to make this shiny soon, but in the mean time, try:

```python
from portingdb.load_data import get_data

data = get_data('data')

for name, pkg in data['packages'].items():
    if pkg['status'] == 'py3-only' and (pkg['deps'] or pkg['build_deps']):
        print(name)
        for dep in pkg['deps']:
            print('    R:', dep)
        for dep in pkg['build_deps']:
            print('    BR:', dep)
```

(FWIW, one thing I learned from this iteration is that storing a densely connected graph in dicts, rather than a database or dataclasses, means that `print`-ing out one thing tries to print out *all* of the data. That probably makes exploring the data way harder than it should be. Sorry!)

**Comment by hroncok** [comment]
For the reference, this is the current result:

- 389-ds-base
  -  BR: libevent
- Io-language
  -  BR: libevent
- alsa-tools
  -  R: python-alsa
  -  BR: gtk2
- asciidoc
  -  R: dblatex
  -  R: lilypond
  -  BR: dblatex
  -  BR: lilypond
- asv
  -  BR: mercurial
- asymptote
  -  BR: xemacs-packages-extra
- aubio
  -  BR: python2
- autokey
  -  R: pygtksourceview
- brotli
  -  BR: python2
- calamares
  -  BR: kf5-ki18n
- caribou
  -  BR: gnome-doc-utils
  -  BR: gtk2
- cgit
  -  R: cherokee
- cinnamon
  -  BR: GConf2
- copr-backend
  -  R: euca2ools
- copr-frontend
  -  BR: epydoc
- copr-rpmbuild
  -  BR: python-rpm-macros
- cryptlib
  -  BR: python2
- cxxtest
  -  BR: dblatex
  -  BR: python2
- d-feet
  -  BR: python-pep8
- dlrn
  -  R: createrepo
- dnssec-trigger
  -  BR: gtk2
- eclipse-pydev
  -  BR: Cython
  -  BR: python2
- exo
  -  BR: gtk2
- flatcam
  -  R: PyQt4
- foxtrotgps
  -  BR: gtk2
  -  BR: libglade2
- frescobaldi
  -  R: lilypond
- git
  -  BR: linkchecker
- gnatcoll
  -  BR: pygtk2
- gnome-dvb-daemon
  -  R: pygobject3
  -  BR: dbus-python
- gramps
  -  BR: gnome-doc-utils
- gtk-doc
  -  BR: dblatex
- gutenprint
  -  BR: gimp
  -  BR: gtk2
- hexchat
  -  BR: gtk2
- hgsvn
  -  R: mercurial
  -  BR: mercurial
- hokuyoaist
  -  BR: python-sphinx
- ibus
  -  BR: GConf2
  -  BR: dbus-python
  -  BR: gtk2
  -  BR: python2
- ibus-bogo
  -  R: PyQt4
- ikiwiki
  -  BR: bzr
  -  BR: mercurial
- kajongg
  -  BR: kf5-ki18n
- kdevelop-python
  -  BR: kf5-ki18n
- kismon
  -  R: pygobject3
- konversation
  -  BR: kf5-ki18n
- libreoffice
  -  BR: kf5-ki18n
- libreswan
  -  BR: libevent
- lollypop
  -  R: pylast
- lpf
  -  BR: python2
- maliit-framework
  -  BR: gtk2
- mate-menu
  -  R: mozo
- mock
  -  BR: python2
- module-build-service
  -  R: kobo
  -  R: m2crypto
  -  R: pyOpenSSL
  -  BR: kobo
- nemo-extensions
  -  BR: pygobject2
- nfs-utils
  -  BR: libevent
- openmpi
  -  BR: python2
- openscap
  -  BR: GConf2
- openscap-daemon
  -  R: dbus-python
- openvdb
  -  BR: epydoc
- pacemaker
  -  R: resource-agents
- pastebinit
  -  R: python-configobj
- pidgin
  -  BR: gtk2
- pitivi
  -  R: pygobject3
- player
  -  BR: gtk2
- pogo
  -  R: pygtk2
  -  R: python-CDDB
- portmidi
  -  BR: python2
- psi4
  -  R: numpy
- pyp2rpm
  -  R: python-virtualenv-api
  -  BR: python-virtualenv-api
- python-aiosmtpd
  -  BR: python-rpm-macros
- python-astral
  -  BR: pytz
- python-atpublic
  -  BR: python-rpm-macros
- python-basemap-data
  -  BR: python2
- python-blosc
  -  BR: numpy
- python-click-man
  -  BR: python-setuptools
  -  BR: python2
- python-django-nose
  -  BR: python-setuptools
  -  BR: python2
- python-flufl-bounce
  -  BR: python-rpm-macros
- python-flufl-i18n
  -  BR: python-rpm-macros
- python-flufl-lock
  -  BR: python-rpm-macros
- python-flufl-testing
  -  BR: python-rpm-macros
- python-fuse
  -  BR: python2
- python-hgapi
  -  R: mercurial
  -  BR: mercurial
- python-htmlmin
  -  BR: python-sphinx
- python-ipyparallel
  -  R: python-jupyter-core
- python-mdp
  -  BR: libsvm
- python-metakernel
  -  R: python-jupyter-core
- python-music21
  -  R: lilypond
  -  BR: lilypond
- python-nmrglue
  -  BR: numpy
  -  BR: scipy
- python-openstackclient
  -  BR: python-os-testr
- python-osc-lib
  -  R: python-os-testr
  -  BR: python-os-testr
- python-poppler-qt4
  -  BR: sip
- python-pyev
  -  BR: python2
- python-pymssql
  -  BR: Cython
  -  BR: python-setuptools
  -  BR: python2
- python-pyrpmmd
  -  BR: python-setuptools
  -  BR: python2
- python-rtslib
  -  BR: epydoc
- python-slip
  -  BR: python2
- python-slixmpp
  -  BR: python-sphinx
- python-social-auth-core
  -  BR: python2
- python-sphinx-theme-flask
  -  R: python-sphinx
  -  BR: python2
- python-subunit2sql
  -  BR: python-os-testr
- python-tasklib
  -  BR: pytz
- python-theano
  -  BR: epydoc
- python-tinycss2
  -  BR: pytest
  -  BR: python-pytest-cov
  -  BR: python-webencodings
  -  BR: python2
- python-virtkey
  -  BR: gtk2
- python-yamlordereddictloader
  -  BR: PyYAML
- python-yara
  -  BR: python2
- python3
  -  R: python-pip
  -  R: python-rpm-macros
  -  R: python-setuptools
  -  BR: python-pip
  -  BR: python-rpm-macros
  -  BR: python-setuptools
- python3-docs
  -  BR: linkchecker
- python3-mypy
  -  R: python-typeshed
- python3-poppler-qt5
  -  R: sip
  -  BR: sip
- quodlibet
  -  R: pygobject3
- rdkit
  -  BR: numpy
- redshift
  -  BR: GConf2
- rpy
  -  BR: numpy
- sagemath
  -  R: Singular
- sediment
  -  R: graphviz
- setroubleshoot
  -  BR: gtk2
- skrooge
  -  BR: kf5-ki18n
- system-config-kdump
  -  BR: gnome-doc-utils
- system-config-language
  -  R: pygobject3
- system-switch-mail
  -  BR: python2
- tito
  -  R: python-cheetah
  -  BR: python-bugzilla
- urh
  -  R: uhd
- variety
  -  R: dbus-python
  -  R: libappindicator
  -  R: pyexiv2
  -  BR: dbus-python
  -  BR: libappindicator
  -  BR: pyexiv2
  -  BR: python-beautifulsoup4
  -  BR: python-pillow
- veusz
  -  BR: sip
- vtk
  -  BR: sip
- waiverdb
  -  BR: pytest
  -  BR: python-click
  -  BR: python-configparser
  -  BR: python-flask
  -  BR: python-flask-migrate
  -  BR: python-flask-oidc
  -  BR: python-flask-restful
  -  BR: python-flask-sqlalchemy
  -  BR: python-gssapi
  -  BR: python-mock
  -  BR: python-psycopg2
  -  BR: python-sqlalchemy
  -  BR: stomppy
- xpra
  -  R: pygtkglext
  -  BR: pygtk2
- zinnia
  -  BR: tomoe

**Comment by encukou** [comment]
I don't think it makes sense to automate this, now that we have the FESCo exception process.
Please reopen if you disagree.
