### ISSUE TITLE
Add info that statuses may not be up to date

### ISSUE THREAD

**Issue by tradej** [fedora-python/portingdb#5]

**Comment by encukou** [comment]
I see two groups in the target audience:
* project managers, who should be able to live with slightly stale data
* porters, who need to check project/upstream status anyway before starting, and whom I really don't want to discourage from filing bugs – if I suggest they need to wait day before filing a bug, it's not going to be filed. (If the amount of filed issues becomes unbearable, then it makes sense to add a disclaimer.)

Am I missing a use case?

**Comment by tradej** [comment]
It's not like that—what I meant to ask was to put on the site (probaby somewhere next to the descriptions of the various statuses) a disclaimer saying something along the lines of 

> The statuses displayed on this page may be out of date.

The managers can, of course, live with slightly out-of-date data, but they must *be aware* that the data is such. Currently, they have no way of knowing unless someone tells them.

**Comment by encukou** [comment]
Well, I'd rather fix the problem than add disclaimers, and I think I don't understand the problem here. But, I realize I'm not a manager.
Is the latest version OK?
