### ISSUE TITLE
FTBFS packages

### ISSUE THREAD

**Issue by frenzymadness** [fedora-python/portingdb#549]
Packages qmtest and pacrunner seem to fail to build from source in Fedora for some time but they are not marker properly in portingdb.

Bugs lists:
* https://bugzilla.redhat.com/buglist.cgi?quicksearch=qmtest&list_id=10347096
* https://bugzilla.redhat.com/buglist.cgi?quicksearch=pacrunner&list_id=10347095

**Comment by encukou** [comment]
portingdb only has a FTBFS *warning*, a heuristic based on the built packages' names – it flags anything ending with `.fcX` with X < 30. It's not meant to be comprehensive.

`pacrunner` built for f30 successfully.
`qmtest` has [minorbump](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_you_need_to_change_an_old_branch_without_rebuilding_the_others), which this doesn't account for, but it's probably not worth the trouble to fix it in portingdb. (But feel free to send a PR if you disagree.)

**Comment by frenzymadness** [comment]
That's all I need to know, thank you!
