### ISSUE TITLE
audit-viewer not recognized as a Python package

### ISSUE THREAD

**Issue by frenzymadness** [fedora-python/portingdb#570]
I am not sure why but audit-viewer package is in the portingdb marked as non-python package although it depends on a lot of python packages and it's written in Python.

https://src.fedoraproject.org/rpms/audit-viewer/blob/master/f/audit-viewer.spec

**Comment by encukou** [comment]
It doesn't actually depend on *Python*. Looks like it it is mispackaged: it uses `/usr/bin/python2`, and assumes one of its dependences will bring that in.

I don't know how we can better detect cases like this. Do you have an objective way to measure "depends on a lot of python packages"? For "written in Python" we'd probably need to examine the file contents of every Fedora package.

**Comment by hroncok** [comment]
We could possibly detect transitive dependencies on Python but that could give us a lot of noise.

We do in fact have *some info* about audit-viewer e.g. here: https://fedora.portingdb.xyz/pkg/python-sexy/

Maybe we can present a reverse relationship page for "non-Python" packages?

**Comment by frenzymadness** [comment]
What about something like:
```
requires = set(requires_defined_in_specfile + real_rpm_requires)
```
Which would catch also packages where a dependency on Python 2 is automatically generated even there is nothing pythonic in specfile.

I don't actually know portingdb internals so sorry if my ideas aren't reasonable.

**Comment by hroncok** [comment]
Note that `requires_defined_in_specfile ⊆ real_rpm_requires` (always).

There is no specfile written Python 2 dependency in audit-viewer.
There is no automatically generated Python 2 dependency in audit-viewer either.

The dependency is transitional.

```
$ repoquery --repo=rawhide --requires audit-viewer 2>/dev/null
/usr/bin/sh
audit-libs-python2
gnome-python2-gnome
gnome-python2-rsvg
libc.so.6(GLIBC_2.4)(64bit)
pychart
pygtk2-libglade
python2-gtkextra
python2-sexy
rtld(GNU_HASH)
usermode
usermode-gtk
```

**Comment by frenzymadness** [comment]
Well, I thought that it has Python 2 dependency automatically generated from some shebang but this usage of Python explains a lot:
```
#!/usr/bin/sh
exec /usr/bin/python2 -O /usr/share/audit-viewer/main.py "$@"
```
Maybe it's just a bad package and we should put it into `fedora-update.yml`.

**Comment by encukou** [comment]
> Maybe it's just a bad package and we should put it into `fedora-update.yml`.

Please don't store any more data in portingdb, if it can be avoided. Send a PR to the package to require `/usr/bin/python2` instead.

**Comment by frenzymadness** [comment]
Ok, sorry for wasting your time.
