### ISSUE TITLE
numpy and matplotlib work under python3

### ISSUE THREAD

**Issue by tomspur** [fedora-python/portingdb#6]
Numpy and matplotlib have python3 packages for Fedora, so they should be marked as released.

**Comment by sYnfo** [comment]
That's right, thanks for the report Tom! :)

**Comment by encukou** [comment]
Thanks for the report!
The numpy entry is fixed now.

The Python 3 version of matplotlib does not provide equivalents for:
* python-matplotlib-gtk
* python-matplotlib-wx

Are those subpackages supposed to be dropped? I can override the status manually, with an appropriate explanation.

**Comment by encukou** [comment]
Or, if matplotlib-wx still needs porting but stuff that depends on matplotlib should be unblocked, I can do that too (by marking matplotlib as *in-progress*).

**Comment by tomspur** [comment]
Good question. I just took over the package quite recently, so ...
This is from the spec file:
`gtk2 never worked in Python 3 afaict, so no need for -gtk subpackage`
I have the same impression for `wx`, but don't know for sure.

Glad, I can help with python3 porting, @sYnfo :)

**Comment by encukou** [comment]
Well, according to [portingdb](http://portingdb-encukou.rhcloud.com/pkg/wxPython/), wxPython is not ported yet. It seems that's the reason for that one.

**Comment by encukou** [comment]
[bz1031172](https://bugzilla.redhat.com/show_bug.cgi?id=1031172) also suggests that :)
