### ISSUE TITLE
packages in "needed for" list lack the exception symbol

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingdb#633]
![_](https://user-images.githubusercontent.com/2401856/68631830-8649d500-04ec-11ea-8d0b-d7218ba938b0.png)

Some of the listed packages here have exceptions, but it is not visible just by looking at them here.

**Comment by hroncok** [comment]
the reverse relation has the same issue:

![_](https://user-images.githubusercontent.com/2401856/68631978-299aea00-04ed-11ea-8539-b909c112e2ec.png)

**Comment by encukou** [comment]
I think it would add too much clutter. Do you think it would be useful?
![image](https://user-images.githubusercontent.com/302922/68654435-34c23a00-052e-11ea-9601-4499f612c71c.png)

These sections aren't very useful for removing py2, IMO. They only show one side of the graph. What are you using them for?
