### ISSUE TITLE
Add the various Fedora spins to Package Groups

### ISSUE THREAD

**Issue by sYnfo** [fedora-python/portingdb#69]
- [x] KDE
- [x] Xfce
- [ ] LXDE
- [ ] MATE
- [ ] Cinnamon
- [ ] SoaS
- [ ] Design suite
- [ ] Games
- [ ] Robotics suite
- [ ] Scientific
- [ ] Security lab

**Comment by encukou** [comment]
Not likely to happen. Even if someone needs it, it's probably not worth it to have this issue open.
