### ISSUE TITLE
Upcoming Bugzilla API change

### ISSUE THREAD

**Issue by encukou** [fedora-python/portingdb#705]
It seems an API change is coming to RH Bugzilla: large results will start to be paginated.
Since I don't use portingdb bug links too much, I intend to spend about an hour adapting to this change (after it goes live), and remove bug links from portingdb if I don't make it.
Let me know if I should put in more effort.

**Comment by hroncok** [comment]
Nah, the bugzillas here are not used any more, if it is too much effort, we can drop them.

**Comment by hroncok** [comment]
Petr, where can I find more info about this?

**Comment by encukou** [comment]
The change is now live and I see it already hit you elsewhere: https://github.com/python-bugzilla/python-bugzilla/issues/149
I heard about the change in Red Hat internal lists; unfortunately I don't know about public announcements.
