### ISSUE TITLE
Handle packages where one RPM depends on both py2 and py3 (e.g. stray shebangs)

### ISSUE THREAD

**Issue by abadger** [fedora-python/portingdb#9]
There's a libvirt-python3 package in Fedora which is supposed to replace the libvirt-python package.  It's not listed on the portingdb app pages, though.  it's a subpackage of the libvirt-python package (which provides both python2 and python3 subpackages.)

**Comment by abadger** [comment]
Reading the page better, I think the problem is better stated as: libvirt-python is ported to python3 but it still shows as waiting instead of ported.  The subpackage that has the python3 bindings is libvirt-python3

**Comment by abadger** [comment]
Found the issue.  It's in libvirt-python's packaging.  An example file is pulling in python2.  I'll fix the package so that no docs pull in extra dependencies to solve that.

**Comment by abadger** [comment]
http://koji.fedoraproject.org/koji/taskinfo?taskID=11696361

**Comment by abadger** [comment]
Just fixed the same problem with the python-urwid package.  Maybe a check could be written for packages where the normal requirements are just for python3 and but there's an additional dependency on /usr/bin/python (or /usr/bin/python2).  For instance, before I fixed it the python-urwi deps looked like this in the fedora.json file:
```
  "python-urwid": {
    "deps": [
      "python",
      "python3"
    ],
    "rpms": {
      "python-urwid-1.3.0-2.fc23": {
        "/usr/bin/python": 2,
        "libpython2.7.so.1.0()(64bit)": 2,
        "python(abi) = 2.7": 2
      },
      "python3-urwid-1.3.0-2.fc23": {
        "/usr/bin/python": 2,
        "libpython3.4m.so.1.0()(64bit)": 3,
        "python(abi) = 3.4": 3
      }
    },
```

So if we looked at python3-urwid and saw that python(abi) is >= 3.0 and libpython is for three but there's also a dependency on /usr/bin/python that's dragging in python2 then we could categorize this as possibly an easy fix for a packager.  If it's something in the docs pulling in the dep then it should simply be a matter of turning off executable bits on the doc files.  If it's a helper script that would require a coder but it's probably still a smaller, more self-contained change than if the whole library is unported python2 code.

**Comment by encukou** [comment]
Right, I'm planning to file bugs for these when I find a moment for it.
I wonder if this needs to go through the mass bug filing procedure?

The full list is:

* PyXB
* avahi
* beesu
* cantor
* dnf-plugin-spacewalk
* libcap-ng
* libsolv
* libvirt-python
* pitivi
* policycoreutils
* policycoreutils
* pyserial
* python-argcomplete
* python-bash8
* python-bashate
* python-cclib
* python-jsonpointer
* python-kombu
* python-mutagen
* python-nodeenv
* python-os-testr
* python-ovirt-register
* python-pecan
* python-praw
* python-pygal
* python-reno
* python-spec
* python-sqlparse
* python-theano
* python-urwid
* revisor
* ris-linux
* subunit
* unbound
* will-crash

and can be generated with:

    $ sqlite3 portingdb.sqlite
    sqlite> SELECT packages.name FROM
    (
    SELECT DISTINCT rpms.rpm_name AS rpm_name, rpms.id AS rpm_id,
    rpms.collection_package_id AS collection_package_id FROM rpms
    LEFT JOIN rpm_py_dependencies ON (rpm_py_dependencies.rpm_id == rpms.id)
    LEFT JOIN py_dependencies ON (py_dependencies.name ==
    rpm_py_dependencies.py_dependency_name)
    WHERE py_dependencies.py_version == 2
    ) AS a,
    (
    SELECT DISTINCT rpms.rpm_name AS rpm_name, rpms.id AS rpm_id FROM rpms
    LEFT JOIN rpm_py_dependencies ON (rpm_py_dependencies.rpm_id == rpms.id)
    LEFT JOIN py_dependencies ON (py_dependencies.name ==
    rpm_py_dependencies.py_dependency_name)
    WHERE py_dependencies.py_version == 3
    ) AS b
    LEFT JOIN collection_packages ON (collection_packages.id ==
    a.collection_package_id)
    LEFT JOIN packages ON (collection_packages.package_name == packages.name)
    WHERE a.rpm_id == b.rpm_id
    ;

**Comment by encukou** [comment]
Since there's so few, I don't think this needs UI changes. But they could be marked with `nonblocking: true`.

**Comment by abadger** [comment]
Sounds good to me.  I wonder if the sql should select specifically for /usr/bin/python2 or /usr/bin/python3.. I guess I'd have to look through the list and see how many false positives there were.

**Comment by abadger** [comment]
How would you like things like will-crash marked where the package is intended to have both python2 and python3 portions.  will-crash specifically is a package that contains programs designed to test that abrt will detect a crash and report properly.  It contains a crashing program for both python2 and python3 so that it can test that abrt handles both python2 and python3 tracebacks.

I guess the desired state would be Done?

**Comment by encukou** [comment]
Yeah. I'll set `will-crash` to `released` in tomorrow's update. This sounds like a very special case though.

**Comment by abadger** [comment]
Been working slowly through the list.  Those should show up when you next update the data.  Ohttps://bugzilla.redhat.com/show_bug.cgi?id=1279704 opened a bug report for python-os-testr since I didn't know if I had analyzed the package's needs correctly: https://bugzilla.redhat.com/show_bug.cgi?id=1279704

**Comment by encukou** [comment]
Wow, amazing! Thanks for the help!
I've updated, and added the bug to the DB.

(Sorry I'm not very active on this this and last week; I'm in PyCon CZ organizer mode.)

**Comment by encukou** [comment]
This is now one of the types of issues tracked by [bug 1285816](https://bugzilla.redhat.com/show_bug.cgi?id=1285816).
For portingdb, I believe showing "in-progress in Fedora" and linking to the bug is sufficient.

**Comment by abadger** [comment]
Yeah, that looks good.  I wish that there was a way to select each type of error -- the ones here are pretty easy to fix once you know the two or three different recipes and when to apply them.

Maybe next time use a different summary in bugzilla for each different type of error.

**Comment by encukou** [comment]
This is now tracked automatically under the "mispackaged" status.
